spring:
  application:
    name: DARAM-server-V1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB-URL}
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  jpa:
    hibernate: ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: 1234
server:
  port: 5000
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: ${SSL-PASSWORD}
    key-store-type: PKCS12
    key-alias: bootsecurity
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    path: /src/main/resources/log
gauth:
  security:
    client-id: ${GAuth-CLIENT-ID}
    client-secret: ${GAuth-CLIENT-SECRET}
    redirect-uri: ${GAuth-REDIRECT-URI}