spring:
  application:
    name: DARAM-server-V1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate: ddl-auto:update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: on
  data:
    redis:
      host: ${Redis_URL}
      port: ${Redis_PORT}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: admin
      password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB
server:
  port: 5000
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    path: /src/main/resources/log
gauth:
  security:
    client-id: ${GAuth_CLIENT_ID}
    client-secret: ${GAuth_CLIENT_SECRET}
    redirect-uri: ${GAuth_REDIRECT_URI}
GAuth-CLIENT-ID: ${GAuth_CLIENT_ID}
GAuth-CLIENT-SECRET: ${GAuth_CLIENT_SECRET}
GAuth-REDIRECT-URI: ${GAuth_REDIRECT_URI}
jwt:
  secret: ${JWT_SECRET}
AWS_S3_ENDPOINT_URL: ${AWS_S3_ENDPOINT_URL}
AWS_S3_REGION: ${AWS_S3_REGION}
AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
AWS_SECRET_KEY: ${AWS_SECRET_KEY}
AWS_S3_BUCKET: ${AWS_S3_BUCKET}
CLOUDFLARE_BUCKET_SUBDOMAIN: ${CLOUDFLARE_BUCKET_SUBDOMAIN}