name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: snowykte0426/daram
          stage: main
          yaml: >
            name: daram-server-v1

            app: java@21

            options:
              ports: "5000"
              env:
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
                - name: DB_URL
                  value: ${{ secrets.DB_URL }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: GAuth_CLIENT_ID
                  value: ${{ secrets.GAuth.CLIENT_ID }}
                - name: GAuth_CLIENT_SECRET
                  value: ${{ secrets.GAuth_CLIENT_SECRET }}
                - name: GAuth_REDIRECT_URI
                  value: ${{ secrets.GAuth_REDIRECT_URI }}
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: Redis_PORT
                  value: ${{ secrets.REDIS_PORT }}
                - name: Redis_URL
                  value: ${{ secrets.REDIS_URL }}
                - name: SSL_PASSWORD
                  value: ${{ secrets.SSL_PASSWORD }}
              buildenv: []
              build: ./gradlew build
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot